#! /bin/bash

echo "Message: directe to django_backend" 
cd django_backend


echo "Message: activate virtual environment" 
source ./venv/bin/activate
echo "Message: virtual environment activated" 

echo "Message: starting django server" 
python3 manage.py runserver
echo "Message: django server started"
