# Generated by Django 5.1.1 on 2024-10-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
