# Generated by Django 5.1.1 on 2024-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[("checking", "checking"), ("savings", "savings")],
                max_length=20,
            ),
        ),
    ]
