# Generated by Django 5.1.1 on 2024-10-23 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_bankaccount_account_type'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalaccounttransfer',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfer', to='bank_account.bankaccount'),
        ),
        migrations.AlterField(
            model_name='internalaccounttransfer',
            name='other_bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_account.bankaccount'),
        ),
        migrations.CreateModel(
            name='CheckImageDepositTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer out', 'transfer out'), ('transfer in', 'transfer in')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('failed', 'failed')], default='pending', max_length=9)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_deposits', to='bank_account.bankaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
