# Generated by Django 5.1.1 on 2024-10-23 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_alter_bankaccount_account_type'),
        ('transactions', '0002_alter_internalaccounttransfer_bank_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckImageDepositTransaction',
            new_name='DepositTransaction',
        ),
    ]
