# Generated by Django 5.1.1 on 2024-11-26 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0003_alter_bankaccount_account_type"),
        ("transactions", "0004_alter_deposittransaction_bank_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "deposit"),
                            ("withdrawal", "withdrawal"),
                            ("transfer out", "transfer out"),
                            ("transfer in", "transfer in"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "completed"),
                            ("pending", "pending"),
                            ("failed", "failed"),
                        ],
                        default="pending",
                        max_length=9,
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                ("provider", models.CharField(blank=True, max_length=255, null=True)),
                ("next_payment_date", models.DateField()),
                ("interval_days", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring",
                        to="bank_account.bankaccount",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
