# Generated by Django 5.1.1 on 2024-11-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0002_alter_bankaccount_account_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("checking", "checking"),
                    ("savings", "savings"),
                    ("retirement", "retirement"),
                ],
                max_length=20,
            ),
        ),
    ]
