FROM python:3.10

WORKDIR /app

COPY django_backend/requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["sh", "-c", "python django_backend/manage.py runserver 0.0.0.0:${PORT:-10000}"]

